name: AuthManager CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        env:
          JWT_SECRET_NAME_POSTFIX: test-postfix
        run: npm test
